name: Scraper Anime Catalogue

# Permissions explicites pour permettre au workflow de pousser des changements
permissions:
  contents: write

on:
  workflow_dispatch: # permet le lancement manuel
  push:
    paths:
      - 'scraper.py'   # déclenche si tu commits le script
  schedule:
    # Exécution hebdomadaire : chaque lundi à 03:00 UTC (ajuste la cron si tu veux un autre jour/heure)
    - cron: '0 3 * * 1'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # nécessaire pour pouvoir pousser avec GITHUB_TOKEN

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests
          pip install beautifulsoup4

      - name: Run scraper
        # Assure-toi que le nom du script correspond (ici : scraper.py)
        run: |
          python scraper.py

      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Ajouter le fichier JSON et committer (si modifications)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -f animes.json ]; then
            git add animes.json
            # Si rien à committer, git diff --cached --quiet retourne 0 => on affiche "No changes"
            if git diff --cached --quiet; then
              echo "Aucune modification dans animes.json — pas de commit."
            else
              git commit -m "Ajout / mise à jour des données scrappées"
              git push
            fi
          else
            echo "animes.json introuvable — rien à committer."
          fi
